# Generated by Django 2.2.28 on 2023-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last name')),
                ('patronymic', models.CharField(blank=True, default='', max_length=256, verbose_name='Patronymic')),
                ('birthday', models.DateField(null=True, verbose_name='Date of birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('telegram_id', models.CharField(max_length=20, verbose_name='Telegram ID')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes')),
            ],
        ),
    ]
