# Generated by Django 2.2.28 on 2023-02-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230207_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Country', verbose_name='Country'),
        ),
    ]
