# Generated by Django 2.2.28 on 2023-02-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_country_users_country_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='most_active',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='Most active user'),
        ),
    ]
